Improve error messages with Netlink event name
During normal POD lifecycle operations, some error messages appear in
sm.log.

i.e:
ERROR: sm-eru[18162]: sm_hw.c(435): Failed to look up interface name, ifindex=66, error=NOT_FOUND.
ERROR: sm[17980]: sm_hw.c(435): Failed to look up interface name, ifindex=66, error=NOT_FOUND.

This occurs because when a POD is deleted, the Calico interfaces are
removed. When the Netlink event RTM_DELADDR arrives for a Calico
interface, the interface name may no longer be available anymore.
In such cases, an error message is generated, which can mislead
debugging analysis.

This fix adds the Netlink event type to the error messages and changes
the log level from ERROR to INFO when the interface name cannot be
recovered for RTM_DELADDR.

Tests Done:
AIO-DX fresh install
POD creation and deletion
AIO-DX host-lock/host-unlock on controller-1

Closes-Bug: 2122680

Change-Id: Ie53f34d32978b453ccb66d5d2e93b5c9a8c0713b
Signed-off-by: Fabiano Correa Mercer <fabiano.correamercer@windriver.com>